version: '3'

services:
  web:
    build: .
    restart: always
    volumes:
      - .:/src
    env_file:
      - web.env
    ports:
      - 8010:8000
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=simcapital
      - POSTGRES_USER=simcapital
      - POSTGRES_PASSWORD=string
    ports:
      - "35432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "gilsonbp@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "string"
    ports:
      - "26543:80"
    depends_on:
      - db