version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=simcapital
      - POSTGRES_USER=simcapital
      - POSTGRES_PASSWORD=string
    ports:
      - "35432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "gilsonbp@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "string"
    ports:
      - "26543:80"
    depends_on:
      - db