# Generated by Django 2.2.6 on 2019-10-27 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simauth', '0002_auto_20191027_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('birth_date', models.DateField(verbose_name='Birth date')),
            ],
            options={
                'verbose_name': 'Capital User',
                'verbose_name_plural': 'Capital Users',
            },
            bases=('simauth.user',),
        ),
    ]
