# Generated by Django 2.2.6 on 2019-10-27 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_date', models.DateField(auto_now=True, verbose_name='Salary Date')),
                ('salary_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Salary Value')),
                ('salary_discount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Salary Discount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('capital_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary', to='capital.CapitalUser', verbose_name='Capital User')),
            ],
            options={
                'verbose_name': 'Salary',
                'verbose_name_plural': 'Salaries',
            },
        ),
    ]
