# Generated by Django 2.2.6 on 2019-10-27 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capital', '0002_salary'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salary',
            unique_together={('capital_user', 'salary_date')},
        ),
    ]
