# Generated by Django 2.2.6 on 2019-10-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capital', '0003_auto_20191027_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='salary_date',
            field=models.DateField(verbose_name='Salary Date'),
        ),
    ]
