# Generated by Django 2.2.6 on 2019-10-27 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capital', '0004_auto_20191027_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salary',
            options={'ordering': ('salary_date',), 'verbose_name': 'Salary', 'verbose_name_plural': 'Salaries'},
        ),
    ]
