# Generated by Django 2.2.6 on 2019-10-27 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('email',), 'verbose_name': 'Usuário', 'verbose_name_plural': 'Users'},
        ),
    ]
